apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: springboot-github-actions-artifactory-100625y 
  janus-idp.io/tekton: springboot-github-actions-artifactory-100625y
  backstage.io/kubernetes-id: springboot-github-actions-artifactory-100625y
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: springboot-github-actions-artifactory-100625y
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml